title: Heather Seymour # your name (or website title) here
logo: "heath.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionated about story telling with data!
   <br><br>
  <a href="https://www.linkedin.com/in/heather-seymour/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
